name: CMake

on: [ push ]

env:
  VCVARS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"

jobs:
  build_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      CXXFLAGS: ${{ matrix.CXXFLAGS }}
      CMAKE_FLAGS: ${{ matrix.ENABLE_TIDY }}

    strategy:
      matrix:
        include:
          - name: x64-linux-gcc-epoll-release
            os: ubuntu-latest
            BUILD_TYPE: Release
            CC: gcc-10
            CXX: g++-10
            CXXFLAGS: "-O2 -DNDEBUG -fcoroutines -W -Wall -Wextra -Werror"
            CMAKE_FLAGS: >
              -DSK_CIO_DISABLE_IO_URING=ON

          - name: x64-linux-clang-epoll-release
            os: ubuntu-latest
            BUILD_TYPE: Release
            CC: clang-11
            CXX: clang++-11
            CXXFLAGS: "-O2 -DNDEBUG -fcoroutines-ts -W -Wall -Wextra -Werror"
            CMAKE_FLAGS: >
              -DSK_CIO_DISABLE_IO_URING=ON

          - name: x64-windows-msvc-release
            os: windows-latest
            BUILD_TYPE: Release
            CC: cl
            CXX: cl
            CXXFLAGS: "/O2 /MD /RTC1 /EHsc /W4 /WX"

          - name: x64-windows-clang-release
            os: windows-latest
            BUILD_TYPE: Release
            CC: clang-cl
            CXX: clang-cl
            CXXFLAGS: "-m64 /O2 /MD /RTC1 /EHsc /W4 /WX"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake (Windows)
        shell: cmd
        working-directory: ${{github.workspace}}/build
        run: |
          call "%VCVARS_PATH%"
          cmake -G Ninja                            ^
              -DCMAKE_BUILD_TYPE=%BUILD_TYPE%       ^
              ..
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Configure CMake (Unix)
        shell: cmd
        working-directory: ${{github.workspace}}/build
        run: |
          cmake                                 \
              -DCMAKE_BUILD_TYPE=$BUILD_TYPE    \
              ..
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Build (Windows)
        working-directory: ${{github.workspace}}/build
        shell: cmd
        run: |
          call "%VCVARS_PATH%"
          cmake --build .
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Build (Unix)
        working-directory: ${{github.workspace}}/build
        shell: cmd
        run: |
          call "%VCVARS_PATH%"
          cmake --build .
        if: ${{ matrix.os != 'windows-latest' }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: cmd
        run: ctest -V
